apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend
- base
commonLabels:
  app: todoapp
images:
- name: todoapp-backend
  newName: us-east1-docker.pkg.dev/todoapp-378301/todoapp-repository/todoapp-backend
  newTag: v1.0.1
- name: todoapp-frontend
  newName: us-east1-docker.pkg.dev/todoapp-378301/todoapp-repository/todoapp-frontend
  newTag: v1.0.3
